export const MIN_WATCH_PERCENT = 90;
export const DEFAULT_MIN_READ_SECS = 120;
export const VIDEO_PROGRESS_SAVE_INTERVAL_MS = 10000;
export const SCORM_POLL_INTERVAL_MS = 20000;
export const MOUSE_IDLE_MS = 5 * 60 * 1000;

export const ANTI_CHEAT_EVENTS = {
  MOUSE_IDLE: 'MOUSE_IDLE',
  TAB_CHANGE: 'TAB_CHANGE',
  WINDOW_BLUR: 'WINDOW_BLUR',
  FULLSCREEN_EXIT: 'FULLSCREEN_EXIT',
};
