import { ROLES } from './roles.js';
import { ROUTES } from './routes.js';

const roleBaseAccess = Object.freeze({
  [ROLES.PLATFORM_ADMIN]: [
    ROUTES.PLATFORM_ADMIN.DASHBOARD,
    ROUTES.PLATFORM_ADMIN.LICENSES,
    ROUTES.PLATFORM_ADMIN.SETTINGS,
    ROUTES.PLATFORM_ADMIN.TICKETS,
    ROUTES.PLATFORM_ADMIN.FEEDBACK,
    ROUTES.PLATFORM_ADMIN.FIGURES,
    ROUTES.PLATFORM_ADMIN.REPORTS,
    ROUTES.PLATFORM_ADMIN.COURSE_PACKAGES,
    ROUTES.COMMON.DASHBOARD,
    ROUTES.COMMON.HOME,
  ],
  [ROLES.COMPANY_ADMIN]: [
    ROUTES.COMPANY_ADMIN.DASHBOARD,
    ROUTES.COMPANY_ADMIN.TRAINING,
    ROUTES.COMPANY_ADMIN.CERTIFICATES,
    ROUTES.COMPANY_ADMIN.TICKETS,
    ROUTES.COMPANY_ADMIN.COURSES,
    ROUTES.COMPANY_ADMIN.PURCHASES,
    ROUTES.COMPANY_ADMIN.PRIVACY,
    ROUTES.COMMON.DASHBOARD,
    ROUTES.COMMON.HOME,
  ],
  [ROLES.COMPANY_EMPLOYEE]: [
    ROUTES.COMPANY_EMPLOYEE.DASHBOARD,
    ROUTES.COMPANY_EMPLOYEE.CERTIFICATES,
    ROUTES.COMPANY_EMPLOYEE.ARCHIVE,
    ROUTES.COMMON.HOME,
  ],
  [ROLES.LICENSE_USER]: [
    ROUTES.LICENSE_USER.DASHBOARD,
    ROUTES.LICENSE_USER.LICENSE,
    ROUTES.LICENSE_USER.STUDENTS,
    ROUTES.LICENSE_USER.COURSES,
    ROUTES.LICENSE_USER.TICKETS,
    ROUTES.LICENSE_USER.REPORTS,
    ROUTES.LICENSE_USER.PRIVACY,
    ROUTES.COMMON.DASHBOARD,
    ROUTES.COMMON.HOME,
  ],
  [ROLES.PRIVATE_USER]: [
    ROUTES.PRIVATE_USER.DASHBOARD,
    ROUTES.PRIVATE_USER.TICKETS,
    ROUTES.PRIVATE_USER.FEEDBACK,
    ROUTES.PRIVATE_USER.PROFILE,
    ROUTES.PRIVATE_USER.CREDENTIALS,
    ROUTES.PRIVATE_USER.NOTIFICATIONS,
    ROUTES.PRIVATE_USER.CERTIFICATES,
    ROUTES.PRIVATE_USER.ARCHIVE,
    ROUTES.PRIVATE_USER.PRIVACY,
    ROUTES.PRIVATE_USER.COURSE,
    ROUTES.COMMON.DASHBOARD,
    ROUTES.COMMON.HOME,
  ],
});

export const PERMISSIONS = roleBaseAccess;

export const canAccess = (role, route) =>
  (PERMISSIONS[role] || []).includes(route);
