export const endpoints = {
  auth: {
    LOGIN: '/auth/signin',
    VERIFY_LOGIN_OTP: '/auth/verify-login-otp',
    REGISTER: '/auth/register/start',
    VERIFY_REGISTER_OTP: '/auth/register/verify-otp',
    REGISTER_COMPLETE: '/auth/register/complete',
    REFRESH: '/auth/refresh-token',
  },
  admin: {
    GET_USER_QR_CODE: '/qr-cards/by-email',
    DASHBOARD: '/incomes/dashboard/platform-admin',
    EMERGENCY_CONTROLS: '/platform-settings/emergency-controls',
    LICENSES: '/licenses',
    LICENSE_BY_USER: (userId) => `/licenses/${userId}`,
    LICENSE_PLANS: '/license-plans',
    LICENSE_PLAN_BY_ID: (planId) => `/license-plans/${planId}`,
    COURSES: '/courses',
    LESSON_CREATE: (courseId) => `/courses/${courseId}/lessons`,
    QUIZ_CREATE: (courseId) => `/quizzes/${courseId}`,
    QUIZ_UPDATE: (quizId) => `/quizzes/${quizId}`,
    QUIZ_PUBLISH: (quizId) => `/quizzes/${quizId}/publish`,
    licence: {
      GET_ALL: '/licenses',
      CREATE: '/licenses',
    },
  },
  user: {
    SETTINGS: '/user/settings',
  },
  subscription: {
    GET_ALL: '/subscriptions',
    CREATE: '/subscriptions/create',
  },
  public: {
    CONTACTS: '/contacts',
    COLLABORATIONS: '/collaborations',
    SERVICE_REQUESTS: '/service-requests',
    REVIEWS: '/reviews',
    COURSES_PUBLIC: '/courses/public',
    COURSE_DETAILS: '/courses',
    COURSE_DETAILS_BY_SLUG: '/courses/slug',
    PAYMENTS_INTENT_COURSE: '/payments/intent/course',
    PAYMENTS_INTENT_COURSE_VERIFY: '/payments/intent/course/verify',
    PAYMENTS_INTENT_COMPANY_COURSE: '/payments/intent/company-course',
    PAYMENTS_INTENT_COMPANY_COURSE_VERIFY: '/payments/intent/company-course/verify',
    PAYMENTS_CHECKOUT_COMPANY_COURSE: '/payments/checkout/company-course',
    PAYMENTS_PAYPAL_COURSE_ORDER: '/payments/paypal/course/order',
    PAYMENTS_PAYPAL_COURSE_CAPTURE: '/payments/paypal/course/capture',
    PLATFORM_STATUS: '/platform-settings/status',
  },
  company: {
    DASHBOARD: '/dashboard/company-admin',
    COURSES: '/employees/courses',
    PROGRESS_REPORT: '/employees/progress-report',
    CERTIFICATES: '/certificates',
    EMPLOYEES: '/employees',
    EMPLOYEE_BY_ID: (userId) => `/employees/${userId}`,
    ASSIGN_COURSES: (userId) => `/employees/${userId}/assign-courses`,
    ENROLLMENT_REMINDER: (enrollmentId) => `/employees/enrollments/${enrollmentId}/reminder`,
    CERTIFICATE_DOWNLOAD: (userId, certificateId) =>
      `/employees/${userId}/certificates/${certificateId}/download`,
    ASSIGNABLE_COURSES: '/employees/assignable-courses',
    MY_PROFILE: '/users/me',
    PURCHASES: '/company-purchases/my-purchases',
    PURCHASE_BY_ID: (id) => `/company-purchases/${id}`,
    ASSIGN_SEAT: '/company-purchases/assign-seat',
    INVITE_EMPLOYEE: '/company-purchases/invite-employee',
    SEND_ACCESS_LINK: '/company-purchases/send-access-link',
    REVOKE_SEAT: (enrollmentId) => `/company-purchases/revoke/${enrollmentId}`,
  },
  licenseUser: {
    DASHBOARD: '/incomes/dashboard/license-user',
    REPORT: '/incomes/dashboard/license-user/report',
    MY_LICENSE: '/licenses/my',
    MY_LICENSE_DETAIL: '/licenses/my/detail',
    PLANS: '/licenses/plans',
    RENEWAL_CHECKOUT: '/licenses/renewal/checkout',
    MY_TICKETS: '/tickets/my',
    CREATE_TICKET: '/tickets',
    TICKET_BY_ID: (ticketId) => `/tickets/${ticketId}`,
    COURSES: '/courses',
    STUDENTS: '/enrollments/licensee/students',
    STUDENT_DETAIL: (studentId) => `/enrollments/licensee/students/${studentId}`,
  },
  enrollment: {
    LICENSEE_STUDENTS: '/enrollments/licensee/students',
    LICENSEE_STUDENT_DETAIL: (studentId) => `/enrollments/licensee/students/${studentId}`,
    PARTICIPANT_SIGNATURE: (enrollmentId) => `/enrollments/${enrollmentId}/participant-signature`,
    CONFIRM_TRAINING_REPORT: (enrollmentId) => `/enrollments/${enrollmentId}/training-report/confirm`,
  },
  certificate: {
    MY_CERTIFICATES: '/certificates/my',
    ARCHIVE_PLAN: '/certificates/archive/plan',
    DOWNLOAD: (certificateId) => `/certificates/${certificateId}/download`,
  },
  archive: {
    PAYMENT_INTENT: '/payments/intent/archive',
    PAYMENT_INTENT_VERIFY: '/payments/intent/archive/verify',
    CHECKOUT: '/payments/checkout/archive',
    VERIFY_CHECKOUT: '/payments/verify/archive',
  },
  enrollmentAccess: {
    INFO: (token) => `/enrollments/access/${token}`,
    REDEEM: (token) => `/enrollments/access/${token}/redeem`,
  },
  favorite: {
    LIST: '/favorite-courses',
    IDS: '/favorite-courses/ids',
    CHECK: (courseId) => `/favorite-courses/check/${courseId}`,
    ADD: (courseId) => `/favorite-courses/${courseId}`,
    REMOVE: (courseId) => `/favorite-courses/${courseId}`,
  },
  private: {
    MY_ENROLLMENTS: '/enrollments/my',
    MY_COURSE_PROGRESS: (courseId) => `/enrollments/my-progress/${courseId}`,
    ENSURE_CERTIFICATE: (courseId) => `/enrollments/my-progress/${courseId}/ensure-certificate`,
    MY_TICKETS: '/tickets/my',
    CREATE_TICKET: '/tickets',
    GET_TICKET_BY_ID: (ticketId) => `/tickets/${ticketId}`,
    NOTIFICATIONS: '/notifications',
    MARK_NOTIFICATIONS_READ: '/notifications/mark-read',
    MARK_ALL_NOTIFICATIONS_READ: '/notifications/mark-all-read',
    MY_CERTIFICATES: '/certificates/my',
    MY_PROFILE: '/users/me',
    MY_CREDENTIALS: '/users/me/credentials',
    MARK_CREDENTIAL_VIEWED: (credentialId) => `/users/me/credentials/${credentialId}/viewed`,
  },
  learning: {
    COURSE_BY_ID: (courseId) => `/courses/${courseId}`,
    LESSON_PROGRESS: (courseId) => `/courses/${courseId}/lessons/progress`,
    LESSON_BY_ID: (courseId, lessonId) =>
      `/courses/${courseId}/lessons/${lessonId}`,
    TRACK_LESSON_PROGRESS: (courseId, lessonId) =>
      `/courses/${courseId}/lessons/${lessonId}/progress`,
    LESSON_STATUS: (courseId, lessonId) =>
      `/courses/${courseId}/lessons/${lessonId}/status`,
    QUIZZES_AVAILABLE: (courseId) => `/quizzes/${courseId}/available`,
    QUIZ_MY_PROGRESS: (courseId) => `/quizzes/${courseId}/my-progress`,
    START_QUIZ: (courseId, quizId) =>
      `/quizzes/${courseId}/start-quiz/${quizId}`,
    SUBMIT_QUIZ: (courseId, quizId) => `/quizzes/${courseId}/submit/${quizId}`,
    SCORM_LAUNCH: '/scorm/launch',
    SCORM_COMMIT: '/scorm/commit',
    SCORM_FINISH: '/scorm/finish',
    SCORM_PROGRESS: (enrollmentId) => `/scorm/progress/${enrollmentId}`,
    ANTI_CHEAT: (enrollmentId) => `/enrollments/${enrollmentId}/anti-cheat`,
  },
};
